### ISSUE TITLE
Stackable items don't return to stacks after Explore is canceled

### ISSUE THREAD

**Issue by aleksey-uvarov** [weatherfactory/cultistsimulator-visible#110]
Hi! I've noticed the following bug. Sometimes the cards that should stack wouldn't do it. More specifically, I do the following:

1. Have a stack of 2 Silver Spintrias.
2. Put the auction house and one Spintria into Explore.
3. Instead of starting the exploration, click the 'x'.

After that, the Spintria returns to its original place, but doesn't stack with the other Spintria.
This happens consistently every time I try it.

I've recorded that behavior here:
https://drive.google.com/file/d/1zaACZrbwH-yYHp14a-sYBg_qSuIg4r6I/view?usp=sharing

**Comment by alexiskennedy** [comment]
Fixed in RIGOLETTO, thanks!
