### ISSUE TITLE
Exile issues?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#117]
In the Exile, Medusa consumes Moth cards but won't give anything in return. Ugh.
Also in the Exile, your previous place of residence isn't gone until you move once more, so you can get new destinations and opprotunities from both towns at once.

https://steamcommunity.com/app/718670/discussions/0/3182361570010152292/

**Comment by alexiskennedy** [comment]
First is fixed. Second is either fixed or was a misunderstanding.

**Comment by Dann239** [comment]
Hey! Sorry if this is the wrong place to report this, but i think i know how to reproduce the second issue. If you reconnoitre while departing, the reconnoitre action gets aborted, but the place of residence doesn't disappear, so we end up with two places of residence!
