### ISSUE TITLE
Risen romance victories are broken

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#124]
When raising a corpse, the old corpse is destroyed because of the consuming slot - invariantly, there's no rite in the game that accepts ingredients in non-consuming slots. Thus, all corpse's mutations are gone - including 'romanticinterest'. Therefore, it's impossible to have a corpse with 'romanticinterest' aspect. Therefore, it's impossible to achieve "...with_risen" variant victories.

Corpse probably needs something like "burnTo": "corpseWith1SecDecayThatHasCrossTriggersToBecomeARisen".

**Comment by alexiskennedy** [comment]
Merging with #111
