### ISSUE TITLE
Is the behavior of drawing cards from a deck containing duplicate elements different than before?

### ISSUE THREAD

**Issue by ClocQ** [weatherfactory/cultistsimulator-visible#130]
1. Issue Description
Is the behavior of drawing cards from a deck containing duplicate elements different than before?

2. Occurred Version
v2022.3.q.1 QUIETPLACE

3. Basis for assuming
(1) Frequency of patrons
When "lore" is used in "talk" to recruit people, there is a 50% chance (by feel) that a patron will appear.
In previous versions, I had the impression that about 80% of the followers were in place by the time all the patrons were in place. However, now, all patrons are often in place before 30% of the followers are in place.
(2) Some cult business's efficiency is too high
I had Forge's apprentice do Cult business and he brings spintria and/or pigment almost every time.
(3) Gold spintria obtained from the Maesoleum of Wolves(vaultrendingmountains4).
After completing the search for the wolf mausoleum, one wolf snow and two gold spintrias were obtained, where previously three wolf snows had been obtained. (Here is a screenshot of what happened.)

![Two gold spintria from Maesoleum of Wolves](https://user-images.githubusercontent.com/85084193/164032375-f12b0dbf-f833-4ff9-8bb8-ec6d617e40d8.png)

**Comment by alexiskennedy** [comment]
Fixed in BRYONY, thank you!

**Comment by ClocQ** [comment]
In BRYONE, I have confirmed that the patron and potential believer rates have been fixed to the 2021 equivalent.
Thanks for the update!
