### ISSUE TITLE
Slow send-to card movement?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#136]
v2022.5.y.1 YERMA via Clocq

1. Issue Description

When right-clicking on a card, movement speed may be reduced

(This simultaneously means that the time until the [Start] button can
be pressed will be extended.)

2. Procedure

(1) Right-click on any card and open "verb".

(2) Right-click on another card before the "verb" is fully opened.

3. Frequency

100%

4. Video

Please refer to the following links.

https://drive.google.com/file/d/1CVOa_x1WXnWcxg3BOlUTknrUI3lxeahZ/view?usp=sharing

**Comment by DaemonUmbra** [comment]
I am able to reproduce this issue in 2022.5.y.2 by double-clicking cards.

The first card double-clicked moves correctly to the verb and gets pre-loaded into the verb's interface.

Double-clicking a second card before the interface finishes its opening animation causes the card's pathfinding destination to change when the interface finishes loading.

Presumably this means the lerp runs twice, once during the interface-opening-animation, and again after it both with the same interval, so the second lerp, being over a shorter distance, happens slower.

**Comment by Chelnoque** [comment]
fixed in HELLEBORE
