### ISSUE TITLE
Constant crashes in ASPHODEL

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#138]
Game often crashes in one of these cases:
a) Returning to the main menu from the tabletop;
b) Continuing the game from the main menu;
c) Purging the save;
(without any mod enabled)

Just starting the game, returning to the menu and pressing Continue causes this consistently on my machine. Attaching the [Player.log](https://github.com/weatherfactory/cultistsimulator-visible/files/8851627/Player.log), but it doesn't appear wee helpful.
Logically, this has something to do with the save file operations. Also, the bug wasn't present in YERMA.

**Comment by alexiskennedy** [comment]
Logically, it might, but it doesn't. It's something about loading the menu scene that does it. I have a bug into Unity about this: it started happening in the last update, but until I saw this I thought it only happened in the editor. I can repro it consistently with Purge, though (even with the save code disabled) so I'll look into that, ta!

**Comment by Chelnoque** [comment]
To narrow (or widen?) the search area, I'll reiterate than continuing the game from the menu causes this too (consistently for me and at least one other person) - so, not just "the menu loading", but possibly all the scene loading, and therefore StageHand is the next logical culprit?

**Comment by Chelnoque** [comment]
The beta came through, can confirm that the bug seems to be fixed - nothing crashed after a reasonable amount of enters and returns in and out of the main menu, as well as intermediary purges.
(the other person was, in fact, Genroa)

**Comment by alexiskennedy** [comment]
Cheers! Were you two running any mods which might have affected the options panel, e.g. custom configs?

**Comment by alexiskennedy** [comment]
ta!

Crashes occurred after enabling the OptionsPanel, even if I had closed it subsequently. Crashes never occurred for me in case (b). Hypothesis: options mod code touched the options panel, bringing the canvas into the player loop even if it was never visible, so it had been enabled when you two folks were hitting Continue. If Continue crashed even with mods disabled, ¯\_(ツ)_/¯, but Occam's Razor suggests it's something in the neighbourhood

cheers, closing!
