### ISSUE TITLE
BRYONY Gridsnap hauntings

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#140]
Gridsnap  size 1:
![20220607201327_1](https://user-images.githubusercontent.com/10981532/172389272-14674b22-d20a-4ca8-ad22-c53630c08daa.jpg)

Gridsnap size 1/2:
![20220607201334_1](https://user-images.githubusercontent.com/10981532/172389330-c6cb10d8-8164-47d8-95a0-9647f06d98e8.jpg)

I moved the verb beforehand to ensure that it's not on the grid and the bug isn't caused by the starting position being somehow janky. Anyways, the position seems blatantly wrong - maybe that can highlight some problems in the snapping algorithm. 
And sorry for the false alarm if this falls within the expected behaviour!

**Comment by alexiskennedy** [comment]
Reported in Dahlia:

You've fixed most of the card drop bugs, but this single issue remains consistent across the last few months of updates:

"Picking up a card and dropping it near to the edge of another card can cause it to appear in a non-sensible place (ignoring the grid). In all my screenshots the drop-preview ghost is accurate, the card will indeed end up there. I note that the drop is pixel-perfect and ignores any grid snapping (except where noted)"

![image](https://user-images.githubusercontent.com/228608/179027778-21b049f8-9c29-4cd0-a01f-da7f12d2bc17.png)

(hs 6630)

**Comment by Chelnoque** [comment]
fixed in HELLEBORE
