### ISSUE TITLE
A Lot Of Font Errors

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#144]
[Player.log](https://github.com/weatherfactory/cultistsimulator-visible/files/8855980/Player.log)

1:
>The character used for Underline is not available in font asset [MenuTitle_Belgrad].
The character used for Underline is not available in font asset [MenuTitle_Belgrad].

And so on and so on.

2:
>The character with Unicode value \u66F4 was not found in the [Text_Philosopher] font asset or any potential fallbacks. It was replaced by Unicode character \u25A1 in text object [ModTitle].
> The character with Unicode value \u597D was not found in the [Text_Philosopher] font asset or any potential fallbacks. It was replaced by Unicode character \u25A1 in text object [ModTitle].
> The character with Unicode value \u7684 was not found in the [Text_Philosopher] font asset or any potential fallbacks. It was replaced by Unicode character \u25A1 in text object [ModTitle].
> The character with Unicode value \u56FE was not found in the [Text_Philosopher] font asset or any potential fallbacks. It was replaced by Unicode character \u25A1 in text object [ModTitle].
> The character with Unicode value \u6807 was not found in the [Text_Philosopher] font asset or any potential fallbacks. It was replaced by Unicode character \u25A1 in text object [ModTitle].

That last one happened because of the mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2816702371
As it can be seen, it uses non-English characters in its name so the game struggles which is understandable but it'd be nice if there were a little 

**Note the the first set of errors happens even without any mod installed (not just enabled - _installed_).**

**Comment by alexiskennedy** [comment]
TextMeshPro in the last Unity update has started emitting more warnings. I'll turn 'em off (and probably regret it later)
