### ISSUE TITLE
Dropping a stack displays card window

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#145]
Each time a stack hits the table after being dragged, the game displays its window info in the corner of the screen. Only for stacks, not for single cards.

**Comment by alexiskennedy** [comment]
ta!

A change in the eventsystem in Unity now means dragging by the stackbadge propagates events differently. I'm going to do this workaround and open a support ticket.

```
        public override bool HandlePointerClick(PointerEventData eventData, Token token)
        {
            if (stackBadge.PointerAboveThis)
                return true;

            return false;
        }
```

**Comment by alexiskennedy** [comment]
(I'm wrong: it's because I switched sort override on in the badge canvas)
