### ISSUE TITLE
Stack ghosts are acting up in BRYONY

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#146]
![madstacks](https://user-images.githubusercontent.com/10981532/172478465-82926f60-2671-42a5-9f51-85da484d6677.gif)

Self explanatory.

**Comment by alexiskennedy** [comment]
Ta - this was also the stack badge sort order

**Comment by alexiskennedy** [comment]
right. I made some changes to canvases and sort order which should have been totally, totally innocuous and really, really weren't. (even that crash bug on the options menu)
