### ISSUE TITLE
(Steam) DLC for Dancer, Ghoul, and Priest are displayed in English at Japanese Environment?

### ISSUE THREAD

**Issue by ClocQ** [weatherfactory/cultistsimulator-visible#147]
(I have sent you an email before, but I guess that you may not have read it, so I would like to report it again here as well.
If this is already known and left unaddressed for some reason, I would appreciate it if you could delete this Issue.)

I'm playing with the Japanese setting, but in the current Steam latest version, the DLC-original sections are displayed in English, even though I have the DLC for Dancer, Ghoul, and Priest.　(At least, this is occurring on BRYONY.)

I found the corresponding DLC file does not exist in loc_jp\legacies, loc_jp\recipes and loc_jp\endings.
I assume this is cause of the problem.
As far as I can see from the files, the same phenomenon seems to occur in the German environment.

I have tried to toggle Enable/Disable DLC in the steam settings and have confirmed that the English version of the file is handled in the form of add/delete, but the Japanese file remains nonexistent.
I have confirmed that it is present in the 2021 version of the BETA.

**Comment by Chelnoque** [comment]
@alexiskennedy _JP and _DE loc files for these legacies are downright missing from the Steam build (probably in GOG too, but can't confirm).

Photoproof: 
![изображение](https://user-images.githubusercontent.com/10981532/177378172-1df90acf-1541-4ca1-b257-77971dd40927.png)

It's not a Unity problem, since local build contains these files, so I assume it must be something with how you ship the build.

**Comment by ClocQ** [comment]
I am attaching a screenshot of the phenomenon, just in case.
I have confirmed that the 2021beta outputs Japanese correctly.
![Issue147_Occurred](https://user-images.githubusercontent.com/85084193/177565002-2f06ab17-729c-4951-ad1a-0649f9a51865.png)

Also, from BETA to DAHLIA, as far as I can tell, there are no 4 files in the Japanese folder except under legacy folder.
![Issue147_File](https://user-images.githubusercontent.com/85084193/177565279-cef4ea63-ae7d-4bc7-9a80-72158eb3a8e4.png)

**Comment by ClocQ** [comment]
Correction confirmed at 2022.7.F! Thank you for your response.
