### ISSUE TITLE
Alt Recipes Text Display Mixup

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#150]
From: https://steamcommunity.com/app/718670/discussions/0/3425564314014123527/

Noticed this too in a few other cases. It seems that, after the recipe ends, the "description" property of an alt recipe is displayed *before* its "startdescription", or, rather, it seems that "startdescription" is displayed again once the recipe ended and the end description is displayed (and the parent recipe's description is displayed for the second time too). 

Test case:
{"recipes": [

  {"id": "recipe1", "startdescription": "recipe1 start", "description": "recipe1 end", "alt": [ { "id": "recipe2" } ]  },
  {"id": "recipe2", "startdescription": "recipe2 start", "description": "recipe2 end" },

  ]}

Notes after starting recipe1:
"recipe1 start" -> "recipe2 start" -> "recipe1 start" (???) -> "recipe2 end" -> "recipe2 start" (???)

This whole thing probably has to do with how alt recipe enabling/disabling handled - it appears that after the warmup ends, all alts are evaluated and "enabled" for the second time.

**Comment by alexiskennedy** [comment]
Thanks! This one sounds 'fun'. I'm going to look at this myself tho because I want a clear handle on what's going on and how it's addressed.
