### ISSUE TITLE
Incredibly small options panel on lower resolutions

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#161]
![20220614172605_1](https://user-images.githubusercontent.com/10981532/173556389-9e64e32e-b17e-45cc-a1ee-8985798e5369.jpg)

Resolution is 1366x768.

**Comment by alexiskennedy** [comment]
2002 called, they want their resolution back :)

Thanks, tho, it needs moving into scalable UI. You know, fiddling with Options this is ultimately the whole reason we got those crashes - it's why it had that extra Canvas
