### ISSUE TITLE
Greedy slot taking multiple cards and crashing game

### ISSUE THREAD

**Issue by flibety** [weatherfactory/cultistsimulator-visible#163]
An 'A Season of Suspicion' verb was searching for reputation cards while I was holding a Notoriety. It pulled the Notoriety from my hand then sent it back to the board and pulled a Mystique. Then my game stopped responding. After a minute or two of waiting it was still frozen so I restarted and it went back to just before the season verb was created.

**Comment by alexiskennedy** [comment]
I think I've seen something similar reported on the forums - if a greedy card grabs a card while the player is holding it, bad things can happen. Logged for fix, thanks!
