### ISSUE TITLE
Newly created verbs not spawning in verb spawn zone

### ISSUE THREAD

**Issue by flibety** [weatherfactory/cultistsimulator-visible#164]
If I have the verb spawn zone moved somewhere when a verb is spawned it sends the verb to the center of the play area and then moves to the drop zone. Happens every/almost every time.

**Comment by flibety** [comment]
This doesn't actually move the cards at the center of the board, it is purely cosmetic

**Comment by Chelnoque** [comment]
fixed in Hellebore
