### ISSUE TITLE
Disappearing lore in research?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#167]
"I got a disappearing card bug in Cultist Simulator today.
I had two level 6 lantern cards, which I studied.
For the first challenge I put in my library.
For the second challenge, I realised I couldn't use my library twice, so I let it time out.
Only one of the two lantern cards came back."

--
This is a 'triple threat' issue: it could be user error, a problem with the JSON recipe logic, or a bug in the code.

[6637.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/8991598/6637.zip)

**Comment by Chelnoque** [comment]
> Only one of the two lantern cards came back.
That's exactly what happens when the lore is successfuly researched. 
Save confirms that everything worked as intended - there's a single Lantern 8 card.

**Comment by alexiskennedy** [comment]
Triple threat.  :) Gotcha, thanks.
