### ISSUE TITLE
Non-intuitive card behaviour on double click

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#169]
Expectations: card floats to the nearest verb.
Reality: not as in expectations.

**Comment by Chelnoque** [comment]
Apparently it's because it checks distance to the slot-in-window, instead of verb-on-the-table:

![doubleclick](https://user-images.githubusercontent.com/10981532/177309305-ee593971-b20b-4633-86be-a40d9d47d628.gif)

**Comment by alexiskennedy** [comment]
Gotcha. Let me be sure I understand. Intended behaviour is

(1) if a window is open and there is a matching slot, then card prioritises that
(2) if >1 window is open with a matching slot, card prioritises that  <-- may not currently be implemented and doesn't matter rn, cos there is a one-window rule in CS
(3) if no windows are open, card prioritises nearest matching slot in a closed verb tile

but if I understand your video correctly 

(1) card prioritises nearest of matching window slot and tiles, even if window is closed?

(does it happen only after the window has been opened more recently than other windows?)

**Comment by Chelnoque** [comment]
> Intended behaviour is

Yes

> card prioritises nearest of matching window slot and tiles, even if window is closed?

Yes

> (does it happen only after the window has been opened more recently than other windows?)

No. It appears that only distance is important.

**Comment by Chelnoque** [comment]
It turns out that the actual result depended not on the distance to the situation token, neither on the distance to the situation window, but on the distance *between* the situation token and the situation window. Makes sense, if you think about it (really hard).
