### ISSUE TITLE
Status bar displays wrong elements after switching legacies

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#17]
![nameless](https://user-images.githubusercontent.com/10981532/156604420-dd2f9455-c673-4b99-8753-3f03f7756cdc.png)
Start the game normally, return to the menu, start Exile - the game will display Aspirant status bar elements. Return to the menu again, start Dancer - the game displays Exile's status bar elements.

**Comment by alexiskennedy** [comment]
Fixed, ta!
