### ISSUE TITLE
Dropzone blocks interactions

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#170]
After clicking on dropzone, it blocks all interactions with its content - clicks don't pass, dropping something behaves as if there's nothing under the cursor. True for both verb and element dropzones.

**Comment by alexiskennedy** [comment]
This was an issue after drag-and-drop of the zone. IIRC, I eventually fixed it by manually setting the sibling order. Probably it needs the sibling order code to run after a click too.
