### ISSUE TITLE
New card zone sometimes layers on top of cards

### ISSUE THREAD

**Issue by CommanderTso** [weatherfactory/cultistsimulator-visible#172]
I'm still trying to get a decent repro for this, but by the late early-game it's happening to me a lot. Steps so far:

- Verb timer completes
- Have the verb spit out its cards
- One or more cards go to the new card zone
- Trying to click-and-drag the card causes you to grab the zone itself, not the underlying card

I'll see if I can pin down what's going on a bit better for you.

**Comment by Chelnoque** [comment]
If you can confirm that it happens after you left-click on the dropzone, then it's probably the same as #170 and will be fixed in the next update.

**Comment by CommanderTso** [comment]
Most likely - I'll close this unless I can reproduce otherwise.  Thanks - sorry for the dupe.
