### ISSUE TITLE
Crash when spawning A Lot Of Items ('KHAINO')

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#179]
https://steamcommunity.com/app/718670/discussions/0/3425564314013438641/?ctp=2#c3419937528173948732

"I noticed that large sets of new, lets call them 'items' gained after a expedition has the effect of crashing my game often."

I've seen this too, but when stress-testing (spawning, like, hundreds of tokens). Logically, on a lower-end machines, that number may be lower. Having a player log will certainly help.

**Comment by alexiskennedy** [comment]
[CultistCrashes.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9233587/CultistCrashes.zip)

**Comment by alexiskennedy** [comment]
[Player.log](https://github.com/weatherfactory/cultistsimulator-visible/files/9233588/Player.log) hs6760

**Comment by alexiskennedy** [comment]
Some crashes! The unique element / redraw may have been a false trail. This looks like maybe a situation lifecycle problem?

```
> Trying to get Output sphere of situation !time_17, but there aren't any; returning null sphere
>>>>>>>> drawseason says: needs is a suitable linked recipe with no chance or challenges specified. Executing it next.
>>>> Situation notification: drawseason has executed and has linked recipe needs. Sending a notification with startdescription of needs.
>>>>>>>> Trying to play SFX SituationBegin: but it was already played this frame
>>>>>>>> Trying to play SFX SituationTokenShowOngoingSlot: but it was already played this frame
> Trying to get Output sphere of situation !time_17, but there aren't any; returning null sphere
> Trying to get Output sphere of situation !suspicion_1066, but there aren't any; returning null sphere
>>>>>>>> Trying to play SFX CardPutInSlot: but it was already played this frame
> Unsticking token with payload ID suspicion and TokenState TravelledToSphere
>>>>>>>> Trying to play SFX SituationTokenRetire: but it was already played this frame
> Trying to get Output sphere of situation !illhealth_1039, but there aren't any; returning null sphere
```

**Comment by alexiskennedy** [comment]
Christening KHAINO
