### ISSUE TITLE
Too many card timers cause performance problems

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#180]
From eight∞#0256 on Discord:

https://cdn.discordapp.com/attachments/456157665035419669/997455325236039680/cultistsimulator_2022-07-15_03-37-02.webm

Effectively, the subject.  Further checks revealed that it's not just "having a lot of tokens" problem", but specifically "having a lot of tokens with a timer". Don't think it's the ticking itself that does the dirty, but events and a collateral of constant event args creation vey well could.

(now, sensibly, it's okay that a presence of a timer requires more performance than an absence of a timer, but the question is "how much more is okay")

**Comment by alexiskennedy** [comment]
The link won't display for me - can you attach a screenie?

I'm putting this in as pri 6 for the moment. I can imagine it being more widespread and unreported though.

**Comment by alexiskennedy** [comment]
"events and a collateral of constant event args creation very well could."

I agree. I've never done any optimisation work to speak of on the pub/subscribe model and I imagine there are some low-hanging perf fruit to be plucked.

**Comment by Chelnoque** [comment]
@alexiskennedy 
Screenshot, obviously doesn't show the problems, but at least you can evaluate the token count:
![изображение](https://user-images.githubusercontent.com/10981532/179767632-a07a583a-7053-4db2-bb20-73a4472c3886.png)

Reuploaded video on the github:
[cultistsimulator_2022-07-15_03-37-02.webm](https://user-images.githubusercontent.com/10981532/179767980-00e167a1-269a-4d20-8066-4747b6b57547.webm)

**Comment by alexiskennedy** [comment]
I'll be interested to learn if this improves in FRAGRANTOLIVE (cf our conversation on #178)

**Comment by Chelnoque** [comment]
Optimized as it can be for timers in Ilex, anything more will require more in-depth tweaks of the events.
