### ISSUE TITLE
Lore combination doesn't work for sixth-degree SH fragments

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#183]
hs6737:

"I did run into an interesting bug after the latest patch, and I know my mod doesn't touch it. It has to do specifically with upgrading two Vagabond's Maps into a Port Noon Anecdote. Only this seems to be affected; all other recipes seem to be working as intended. But when I try to make fragmentsecrethistoriesg, I get this:
https://d33v4339jhl8k0.cloudfront.net/inline/80948/2d93341ee688884cc3f35b65030e54bcd4ae3c58/94809d005fc5559a8c82b503d854b646af431e5e/72459139EBC84563BDAB7ABF7E3DF988.png

Breaking out the debug tool, I've tried combining other lores of various aspects, including lower tier SH lores. But I think I know why this is happening:

Correct me if I'm wrong, but I think the way the upgrade itself is scripted is to use the XTrigger to upgrade both, and then the "aspect": -1 command removes one of the two, along with "project": -1 to remove the temporary card. The problem with that would be that a Port Noon Anecdote is Unique… so one is immediately being removed, and then the "secrethistories": -1 command is hitting the other one."

==

If the user is right about the cause, this might have similar consequences elsewhere (especially in mods) so I'm calling it pri 4 if confirmed.

**Comment by Chelnoque** [comment]
So that how it feels to be on the other side of the report.
(an extremely helpful and insightful report, must I add!)
