### ISSUE TITLE
Tags for mods

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#185]
Wait what? AK adding a modding feature request?? Yes, tho not at a wildly hi pri.

I've specified a number of tags for mods that modders can apply. I always assumed this was something that happened on the Steam workshop page. If I understand correctly, though, it's something that needs to be specified via the API at mod upload.

The mod tags I originally provided were off the top of my head, so if Chel or anyone thinks we could make use of more tags, do say.

**Comment by Chelnoque** [comment]
Added in JUNIPER.
