### ISSUE TITLE
Expulsion limits are broken? 

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#186]
![изображение](https://user-images.githubusercontent.com/10981532/180938273-80050c5c-f888-41d3-a584-bd66110c12aa.png)

All health/passion gets scarred in dances, despite the limit: 1.

**Comment by Chelnoque** [comment]
Aha, and it's another stacking cards issue. Expulsion code is written with an expectation that all tokens it operates on have quantity 1 (which, as we know, was *usually* the case previously). Thus, a stack of three healths/passions is a single token for it.

**Comment by Chelnoque** [comment]
Addendum for priority measurements: 
As far as I can tell, the case described here is the one of its kind (well, a cluster of its kind - it affects alll dancer scar recipes). In other cases expulsions are used on the things that are either unique (for ex. followers in expeditions) or can't be present in a quantity more than 1.

**Comment by alexiskennedy** [comment]
This is the hotfix we just pushed to FRAGRANTOLIVE?

**Comment by Chelnoque** [comment]
Correct. Closed.
