### ISSUE TITLE
Korean Loc Can't Display Korean Characters

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#188]
https://steamcommunity.com/sharedfiles/filedetails/?id=2236735768
3K subscribers are forced to use the old version, no joke.

Latin fontscript supports them in legacy, but not in the new version, apparently?

**Comment by alexiskennedy** [comment]
No joke indeed. Calling it a pri 3.

*However* is this an issue with the language mod not specifying cjk fontscript? If so it's an easy fix for them rather than us.

**Comment by Chelnoque** [comment]
It was both. The mod doesn't use cjk, but cjk is unable to display Korean anyway because it's atlas population is set to static (and its connection to the original font file is lost).
