### ISSUE TITLE
Dropzone in 1-snap placement issue

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#191]
(hs6827)
Here is an issue in [FRAGRANTOLIVE] right now: Currently when playing with the 1-card grid enabled, the card output thing (where new cards get placed) is offset by half a card [...] Even when moving it around wich the grid set to 1 card, is snaps to the 1-card grid but it's offset by half a card, so it never lines up with the cards.

**Comment by alexiskennedy** [comment]
This is barely a pri 5. I would mark it pri 6 but anything around gridsnap tends to cause distress.

I would be very surprised if this is new to FRAGRANTOLIVE - I assume it was in previous versions.

**Comment by Chelnoque** [comment]
fixed in HELLEBORE
