### ISSUE TITLE
If game was unpaused, time passes on Save & Quit

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#193]
1. Game is unpaused.
2. You press ESC.
3. Game is paused.
4. You press Save & Quit.
5. Time passes (in the real world) while the game saves.
6. Right before the game leaves the tabletop scene, you can see that in-game timers slightly changed.

**Comment by alexiskennedy** [comment]
Details of subj unclear :) Is it failing to pause on save, saving in an inconsistent state, or? This could be a pri 7 or a pri 3

**Comment by Chelnoque** [comment]
Subj clarified! 
But I did a bit more testing - the save still loads correct, pre-pause timer values.
So while it can alarm people, the problem here is only the UI one.

**Comment by alexiskennedy** [comment]
I'm surprised how relieved I am by that. Thanks.

If the UI bug has been there for the last few versions, I would even make this pri 9.

**Comment by Chelnoque** [comment]
(I'm fairly sure it's here since the rewrite)

**Comment by alexiskennedy** [comment]
No more reports, it's clearly not worrying people
