### ISSUE TITLE
Camera WASD problems

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#194]
Zuris#4495:
"Is anyone else experiencing a constant problem with trying to move around via WASD randomly selecting your character's name and overwriting it?"
"WASD-based camera movement isn't bounded like mouse-based camera movement is"

**Comment by Chelnoque** [comment]
Disabling UI navigation from charname input field - should help with the first.
Will look at the second one later.

**Comment by alexiskennedy** [comment]
When you get to disabling UI navigation, can you ping me particularly to look at the commits? There are some traps around hotkey work.

**Comment by Chelnoque** [comment]
Second one is fixed in HELLEBORE.
