### ISSUE TITLE
f.6 crash

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#195]
hs 6853 FRAGRANTOLIVE.6

"My game has crashed consistently to desktop whenever I try to fully play through a game, this is the first time I got a screen ingame"

[Attachments.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9336508/Attachments.zip)

pri 4 because I've only seen this report so far.

**Comment by Chelnoque** [comment]
Yay, a crash that can be recreated!

**Comment by Chelnoque** [comment]
Somehow, seasonevents deck initialized several times (not even "twice" - SEVERAL times).
Reasonably easy to apply band-aid, but at loss how it could happen normally.
