### ISSUE TITLE
Window sizing / aspect overlap issue in f.6

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#196]
"First time bug reporting for any game ever, hopefully it ends up ok. So I just installed the latest version from GoG on top of my old version( 2021.1.b.2_(44603) ), and when I went to paint, the slots to put passion, mystique, etc (Art or Bread) covered over the little icons on the bottom of the Paint window. I imagine this is unintended, maybe some scaling issue? I've attached a screenshot as well as the save, config, Player, and Player-prev files."

hs 6847

He did just upgrade from the classic version, so it's *possible* it's a hiccup from the old save format.

[Attachments (1).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9336510/Attachments.1.zip)
"

**Comment by Chelnoque** [comment]
Checked, 100% legacy problem, can be reliably recreated after a conversion, can't be caused without.

After a testing, it appears that the problem resolves after the recipe runs in a verb for the first time in a converted save. 
@alexiskennedy can you please confirm that it's the case? If yes, probably not pri 5.

**Comment by alexiskennedy** [comment]
I'll check with the gent, and close it in the meantime. If it's a one-off legacy issue then not even pro 9
