### ISSUE TITLE
Chinese loc broken in the latest version of the game...

### ISSUE THREAD

**Issue by KostberaLili** [weatherfactory/cultistsimulator-visible#20]
![WRDIZP1{CBJ5 5`Z)GW0Q{C](https://user-images.githubusercontent.com/72067242/156741649-06144869-8c4c-4fa0-8fd3-fac184e51507.png)
The texts in the recipes are tofus now...

**Comment by alexiskennedy** [comment]
Fixed in upcoming 2022.3.b patch.
