### ISSUE TITLE
Small UI overlap (pagination arrows in Situation Window)

### ISSUE THREAD

**Issue by Genroa** [weatherfactory/cultistsimulator-visible#200]
Even when the situation window has the space to display text properly without shrinking it massively, any text long enough to use the entire height of the window can lead to this kind of overlap: the pagination arrows overlap the text, making it a bit less easy to read. See picture below.
![image](https://user-images.githubusercontent.com/4357574/186228043-03b4d8d3-5170-4817-bdbb-da01e285b2b7.png)

Would it be possible to move them slightly out of the way?

**Comment by Chelnoque** [comment]
Fixed in ORACHE along with other situation window text display enhancements.
