### ISSUE TITLE
At widescreen-ish sizes in windows mode, there are onclick problems with aspect icons in the info window

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#201]
from hs 6888. If you have trouble reproducing, make the whole window very wide and then slim it down.

Chel, this would be pri 7 but I'm concerned that it might affect other UI elements, might carry over into BH, and widescreen is increasingly 
-  thing.
- It may be easily reproducible in-editor with the scaling tool
- it could conceivably be a Unity bug! so if you're struggling to find a fix, hit support.
- 
==
This is on the current up-to-date Steam patch. Non-beta.

Expected behaviour: Clicking on an Aspect's icon (in an Info Window) will display a tooltip about that aspect.

Observed behaviour: In windowed mode, shortening the Y-size of the screen will move the "clickbox" of the Aspect straight downward from the actual visual icon. This downward shift will be larger the more the Y-size is shortened. This means that clicking on an Aspect's icon will, often, not display a tooltip.

Reproduction steps:

1) Open Cultist Sim.

2) Set game to windowed mode.

3) resize the game window so as to make it shorter in the Y direction. Make it roughly 1920x600. Example:

image.png

4) Click on a card, e.g. Health, so that its Info Window appears in the top right corner.

5) Attempt to click on an Aspect (e.g. Aspect: Ingredient). You probably won't be able to click it.

6) You will note that the "hitbox" of the Asp1474very significantly. Almost halfway down the screen!

The more you decrease the Y-size of the screen, the larger the downward shift is.

That said, even minor decreases in the Y-size (example: try 1920x1020, instead of 1920x1080) will cause this "hitbox shift" to happen. For minor decreases, only the Right-Most Aspect is affected.

*note that 1920x1020 is a fairly natural resolution to play in, if you put the game in Windowed mode and then use the Window-Fullscreen button so that you can see the entire screen but also your taskbar. e.g.:7

**Comment by Chelnoque** [comment]
More problematic than just aspect display - everything right-aligned in UI gets mis-casted (menu buttons for ex.).

But defo a Unity thing, not present in 2020 version. Did them a bother.

**Comment by alexiskennedy** [comment]
>Did them a bother.

I think autocorrect intervened here?

**Comment by Chelnoque** [comment]
Tried to say that I wrote them. But it's good to know that when AI conquers humanity I will be able to mimic.

**Comment by Chelnoque** [comment]
In words of Alex Pritchard for Unity Support:
> This issue seems to be related to an existing issue surrounding GraphicRaycaster. The issue has been fixed, and the fix is within the next version of 2022.1. The planned release for 2022.1.15f1 is this week, although as with any release date this might shift - we'll be sure to let you know when 15f1 is out.

Possibly can wait till full 2022.2 transfer.

**Comment by Chelnoque** [comment]
Fixed by updating to 2022.1.15.f1.
