### ISSUE TITLE
Lag in alt description display

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#208]
KatTheFox#3098:
"also in the new update to main i'm getting significant lag with verb descriptions. like if i start a verb, or put a new card in, it seems to take a little while to recalculate alts so it goes back to the 'default' description for a second
for example i have an Expedition running rn. if i add a Skaptodon Tooth to the empty slot, the title changes to 'A Busy Night Lies Ahead' before back to the correct title (Violence is a Solution)"

**Comment by alexiskennedy** [comment]
Pri goes up if we get a log or other reports

**Comment by Chelnoque** [comment]
Fixed in PEONY.
