### ISSUE TITLE
Revert automatically to corrupted saves for backup

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#212]
I added some code a while back that looked for a valid backup save if the current save has invalid json (the 'cat jumped on my power button' error)

But I think it either isn't working or is only sometimes working - I seem to still get help requests from people with a corrupted save and good backup saves.

I believe it only looks at the first backup save to check for corruption, because I didn't want to roll back too far without user intervention - it might be worth looking at first two saves if so.

See also #211

**Comment by alexiskennedy** [comment]
211 has addressed mod-borked problem
other fatal save issues ('cat power button problem') also go to menu screen with warning instead of cat screen
CONTINUE button is enabled, not disabled (if they load a fatally wounded save file, they end up on cat screen)
auto-reversion to backup is disabled
REVERT TO BACKUP button is implemented as part of popup

**Comment by Chelnoque** [comment]
Implemented in LONGIFLORUM
