### ISSUE TITLE
Gatekeeper mod

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#219]
(1) new WF-sanctioned mod, GHIRBI, which does only two things: (i) allow mods which rely on DLLs to be enabled and (ii) provide text explaining this.
(2) Mods which rely on DLLs cannot be enabled unless GHIRBI is installed and enabled.

-- I think, for now, we should hold off on confirmation warnings as well as this. The burden of clicking OK when enabling/disabling several mods sounds high. GHIRBI is effectively an indication that mods should run with elevated privileges. Any sysadmin would tell us this is a risky idea, but it's less risky than we have right now.

**Comment by alexiskennedy** [comment]
Chelnoque suggested conf warnings as well as gatekeeper mod does sound safer: I agree.

**Comment by Chelnoque** [comment]
Present in NEMESIA
