### ISSUE TITLE
Followers lose follower aspect?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#222]
Only one report so far, from k.3

Sylvia has a -1 follower mutation. The only -1 follower mutation recipe I can see is the wounding one, and healing should restore the follower aspect.

My first suspicion is user error, but the reporter seems bright and informed.

It seems to be the German loc.

===

[hs7142]

Hi there,

since the latest update some of my followers lose the follower aspect after some time. I don't exactly know when this happens, but afterwards I can't use them for anything else but the Speak verb (which only says that we have nothing to discuss).
I have attached my log and save files. In my save, Sylvia is affected by this. She previously was a disciple and I used her before for different vaults. In line 16250 of the savegame file, the "follower" value has been set to -1. I don't know why this happened, but deleting this line lets me use her as before. This happened twice to me now and never before the update, so I think it's a newly introduced bug.
Thank you for time!
[Attachments.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9868539/Attachments.zip)

Best regards,
Jeremias Bohn

**Comment by alexiskennedy** [comment]
"thanks for the quick response! I am not 100% sure, but it might be that she was wounded. I remember that at least one follower was wounded, but I don't exactly remember if it was her. However, the first time this happened was with Tristan, who had already been promoted to reshaper. It happened to both of these followers during my run with the Apostle Aestuant legacy (this is the only run I did so far with the latest update) - Tristan was the follower I received from Our Cause after working the Our Favourite Place card and the bug occurred very early on for Tristan, I don't think he was wounded.
I play with the German localisation, that's correct (I found a minor localisation error, too, Violet is called Victor on her card)!
I will probably start a new game tonight and I will try to keep an eye on my followers - if I find a reliable way to reproduce this bug or any further information, I'll let you know!"

**Comment by Chelnoque** [comment]
More than a month later, I can confidently state that, presently, this bug if not non-existent, then at least vanishingly rare. Nothing in JSONs, both original and loc_de, may lead to a situation when "follower": -1 can be present without "follower_wound": 1. Nothing in code suggest that one mutation can be executed while other didn't.
Maybe we somehow fixed it without realising.

**Comment by alexiskennedy** [comment]
Cheers. I'l take it to pri 7, and close it if we see no recurrences after the Christmas sale (highest traffic period of the year)
