### ISSUE TITLE
Suppression Bureau logic quirk?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#224]
Typically detailed report from Clocq. Can you take a look and see if they're right? I haven't looked at this logic in years...

===

I was looking at hunting.json and found a description that may possibly be a bug. I am reporting it just in case.

When rival is caught by the Supression Bureau, I think that when Favour is throwed in, it will transition to suspicion_favourused. (1)

In "Suspicion_favorused", neither "suspects_rivalimprisoned" nor "suspects_rivalexonerated" appear to be 
![e63hMQyDf6SoRArX](https://user-images.githubusercontent.com/228608/198989245-45497c63-6920-4edc-9db5-530b52d04b08.png)
![mem0a2zgF6ysFqfm](https://user-images.githubusercontent.com/228608/198989246-8fba60fc-d28b-4032-ac6d-d663b29531c0.png)
![9HR0AyFA4eTneRMS](https://user-images.githubusercontent.com/228608/198989247-f2248e2d-1082-47e1-957a-540915339453.png)
present at the destination.
This makes it appear that there is a 70% chance of a "suspicion_meexonerated" transition and somehow "Me" release will occur. (2)

If the use of Favour fails, the "me" arrest event will appears to be in progress as it goes to "favourused_failure", I think. (3)

I haven't actually tried it yet, so there is no way to say for sure that this will be the case, but I am happy to report that it will be.
I apologize if I have misunderstood.

**Comment by Chelnoque** [comment]
Clocq is absolutely right! Fixed.

**Comment by ClocQ** [comment]
Glad to be of service! I'm glad I reported it.
