### ISSUE TITLE
Unspecified crash issue

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#226]
LONGIFLORUM, save created in KALMIA.

'Keeps crashing' - user says there's no player.log, I'm trying to track that down.
[save.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9970492/save.zip)

[hs 7237]

**Comment by Chelnoque** [comment]
Lore subversion in the save - apparently, it's CONSUMMATUM.

**Comment by Chelnoque** [comment]
Crashed where the CONSUMMATUM crashed, got fixed when CONSUMMATUM got fixed. Therefore, it was CONSUMMATUM.
