### ISSUE TITLE
Unspecified crash issue, player log included

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#227]
(LONGIFLORUM,no mods afaict)

[Crash Report.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9970498/Crash.Report.zip)

(user adds "You've given me many hours of happiness and fulfillment with this game, and I appreciate all of your efforts.", which isn't relevant, just nice.)

[hs 7238]

**Comment by Chelnoque** [comment]
Pretty strange. The course of events seems to be:

- Player returns to the main menu from the game
- Game reports a successful save, and creation of a backup
- Player presses "Continue"
- Game: "Whoops, there's no save file" and crashes

And the save file indeed is missing from the report, while the latest backup is present.
I'm very carefully voicing a suspicion that the file may be actually deleted by the user? Perhaps in expectation that the game will load backups automatically?..

Anyways, added a safety net for cases when the game somehow entered the menu with the valid save, but leaves it without.
