### ISSUE TITLE
Crash CONSUMMATUM - game crashes on completion of some recipes

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#228]
LONGIFLORUM

"I completed my first commission and the patron went on cooldown. The moment the cooldown ends the game just crashes. I launched the game several times hoping it'd fix itself, but it starts me 10 seconds before the cooldown ends and crashes again when it comes to 0."

[Attachments.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9970533/Attachments.zip)

hs 7239

**Comment by alexiskennedy** [comment]
"i send you my logfiles and hope you can help me.
The game crashes every time my study ends or get to the next step."

[Attachments (1).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9970607/Attachments.1.zip)

[hs 7243]

**Comment by alexiskennedy** [comment]
I think this is the same issue [hs 7241]

[Attachments (2).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9970621/Attachments.2.zip)

**Comment by alexiskennedy** [comment]
[hs 7247]

"Thanks for checking this out! Game was buggy before the crash - lots of 1 second cards, or after dreaming seeing all possible options. "

error log looks like CONSUMMATUM

[Attachments (3).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9970654/Attachments.3.zip)

**Comment by alexiskennedy** [comment]
My game keeps crashing - seemingly whenever the timer runs out for merging a chalice lore and a moth lore. 
[Attachments (4).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9970661/Attachments.4.zip)

[hs 7250]

**Comment by alexiskennedy** [comment]
"I was playing Cultist Simulator today when I encountered this issue with the game crashing. The game was recently updated, so I imagine it may be related to a change to the game. Loading my save will consistently result in a crash at the time when the Study verb resolves. There is also a graphical glitch that occurs when tapping on an empty slot, producing a large glowing sphere of pink light. The Talk verb was empty at the time of the autosave, so you can test this for yourself easily."

[Attachments (5).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9970676/Attachments.5.zip)

[hs 7252]

**Comment by Chelnoque** [comment]
Caught, DLC-related. Conversion turns things into husks. Husks are defined in Exile.

**Comment by alexiskennedy** [comment]
[hs 7251]

[Attachments (7).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9970707/Attachments.7.zip)
