### ISSUE TITLE
Forbidden restrictions in greedy slots broken? VETITUM

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#229]
[LONGIFLORUM]

"greedy slots that also have a forbidden section dont act as they should, instead of excluding the specified elements or elements with specified aspects, they exclude EVERY card. Off the top of my head it breaks all of the Ever After endings, possibly more. It doesn't affect slots with forbidden elements that are not greedy, those work properly, it's only specific to the greedy slots. "
 
no screenshots or log files, and I'm surprised there haven't been more reports if this is the case - but another user reports what appears to be a similar problem.

[hs 7240]

**Comment by alexiskennedy** [comment]
Same bug, very detailed description below. This user does specify mods, so this may be mod-related.

===

Hello!

I'd like to report a bug.

The Short:

As the image bellow suggests this event is not taking my health, thus causing me to loose no matter what I do.

The Long:

(I wonder what a long would think of the modern world now? Heck, the various names/hours etc! - oh right sorry tangent aside)

- So I won my first "major victory" going the path of enlightenment. Afterwards I jumped right into the newgame+ for a while. After a while I decided I'd really like to start a fresh run to try some other cults out and other ways of doing things. But I didn't want to loose my save! So I took the save.json file, and wrote a new name on it. (I assumed the game would just recreate the save file from scratch)

- I start a new run, this time going with Hydra and wanting to see if I could recruit all the rivals.
-- But, after a bit of this I decided it be fun to try a Moth-run, now that I understood some things about influences and how moth really has a large amount of them.

--- So I do the same thing and start a new run with a new save with moth!

---- couple days later I'm wanting to get further in my newgame+ lantern run so I save a copy of my current moth one, return the original save file to save.json

---- Now, I will mention, all other times I would be quite out of the game while making these edits and... I forgot to do that this time. Figured worse comes to worse I can just reinstall the game or just reset it if something goes wrong.

--- For a while nothing seemed off... but then the first weird thing happened:
The Weary detective was not taking my reputation cards.
Then I noticed cards weren't being taken for facination checks either.
Then I noticed when I went through the stag door 2 cards were super imposed in the center of the screen... I tried to ignore them and instead chose the base card at the stag door.
Those two cards in the middle stayed there, so I tried dragging them off... and it seems like I got one reward for each door. Knife - key - grail - forge influence some eurodition a facination (maybe something else).

--- Then finally the health check came around. And it killed my run. I was kinda bummed... but I figured "maybe I broke it from my meddling with save files. So... heck I'll just reset and start over" So I "verified game files" with steam, and started a new run. This time choosing the well to do start.

And the same issue now pops up.

I may try next to purge my entire run (which sucks cus I guess that means anything that might carry over will go away.. .which really sucks due to how much I invested in time for the run I won on. (literally got every single book, every scrap of lore, all the paintings, did all the locations, got all the cultists, even recruited one rival, killed the others, made all the paintings... literally did everything I could think to do before I completed the game... I was hungry for that lore XD haha )

If purging my run doesn't work... I'm not sure? (( went ahead and just attempted a clean purged run... still same issue, season of illness comes up and I die due to not pulling health))
The only other thing I can gather is the game was update today though there were no patch notes. Maybe something there has caused this issue? (i still have my old save file so would be nice~ Um... guess I'll add that in too so you can see)

Hope that was detailed enough!

Oh uh... just incase it matters though I don't think it would: I use a few mods mostly for quality of life/time saving.

* The Roose Machine (1.5.136) -- needed for other mods
* Color Fixer (1.0) [since I already know every cultist's main attribute, this just makes it easier to remember at a glance, changing follower card' colors to their aspect. Speaking of... perhaps it would be a nice quality of life thing to have followers change their card color to indicate their aspect better? Not before you get them in the cult, obviously, to keep that part a mystery at first.)
* Forecast Rework (1.0) [another quallity of life thing, makes the time box icon show the upcoming event so I don't have to click on it each time I wanna check]
* Adjustable Fast Forward (1.1) [Gotta go FAAAAST]
* Improved Skintwisters (1.0) [apparently skintwisters were tuned to be a much lower chance than all other exalted followers at doing their thing... I heard like 50 or 70 percent chance at level 10!? This mod puts their chances in line with all other exalted. One of my first games I went moth cult and got utterly obliterated when my raw prophet and then 3 exalted moth followers couldn't take care of level 1 evidence..... all in a row... like Moth is chaos, so obviously it makes since to not always work.... but 4 failures in a row seems much less chaotic to me XD )
* Shelves (1.2.12) (as seen in the picture, useful for quickly organizing items. When Ipress the condense button or tab the cards all go find their place)
* More Shelves (3.1.2) -- more of the above
* Smart Lore Shelf (1.1.0) - a more condensed shelf for lore.

**Comment by Chelnoque** [comment]
This one is already sorted, was a mod bug.
