### ISSUE TITLE
'Cards not being returned from verbs'

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#235]
(hs 7304)

"Cards not being returned from verbs. Just lost the final health upgrade card in this save."

Only report, and unconfirmed - here are the files.

[Attachments (1).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10055725/Attachments.1.zip)

**Comment by Chelnoque** [comment]
Health skill is present on the normal save.json. 
![изображение](https://user-images.githubusercontent.com/10981532/203031481-df8bd8de-44eb-4472-aa3f-6d0df6fff477.png)

Hypothesis: user mixed the icon with Restlessness. Can you, please, politely confirm whether it is or is not the case?

**Comment by alexiskennedy** [comment]
![image](https://user-images.githubusercontent.com/228608/203035252-2bb7f51c-655a-4773-8a50-42c519826988.png)
Commencing British tact deployment

**Comment by alexiskennedy** [comment]
"Hello,

No, it looks like the card I thought disappeared is there.

Now I'm regretting restarting the previous game where Moreland's Shop disappeared within the first few minutes of the game. I guess I'll just keep an eye out and see if it happens again."

:)
