### ISSUE TITLE
Description window goes astray

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#237]
Intermittent weird window issue?

@Chelnoque you may remember responding to this lady (see 1.jpg). I asked her to disable mods, cos there were loads, and she says  "Hello. I disabled all mods, deleted the "save.json" file, purged the in-game save, but the problem is still there. However, this has become less frequent."

[window_issues.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10165435/window_issues.zip)

Only report I've seen.

**Comment by Chelnoque** [comment]
A "video" is mentioned in Steam discussion. Was it send after all, and if yes, can I see it? I'm still not 100% sure I understand what the problem is.

**Comment by alexiskennedy** [comment]
aha, yes! (it was an embedded link so it didn't end up in the zip file)

https://drive.google.com/file/d/1Mq4ubq5PO9t369oXpw3rfoBcimIQ0EP2/view

**Comment by Chelnoque** [comment]
The bug looks hella like an exception in situation window display, and the game appears to be heavily modded, including DLLs, so my initial bet is on that. Will try to recreate.

**Comment by alexiskennedy** [comment]
They did say they've disabled all mods and purged the save... but 'less frequent' may mean 'different problem with a similar symptom that doesn't appear in the video'

**Comment by Chelnoque** [comment]
Another thing that catches the eye is that the game on video runs in pretty low FPS (unless that's a video thing). Tried that avenue, no luck for now. Added some precautions in that regard anyway, but I don't think this is it. Will look further.

**Comment by Chelnoque** [comment]
Recent developments:
a) Precautions didn't work
b) But got another report with confirmation that it's a FPS issue after all

**Comment by Chelnoque** [comment]
Other *theoretical possible future* silent errors which may be or may not be related to low FPS.
