### ISSUE TITLE
INVISIBLE SERAPEUM -> SIXTH HISTORY

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#238]
just needs the icon and name changing. I'll update it at the workshop end.

**Comment by Chelnoque** [comment]
Makes sense to do together with Gatekeeper release (scheduled at Nemesia release?)

**Comment by Chelnoque** [comment]
(also it's the window where the vanilla legacies are, but I guess you can't have everything)

**Comment by Chelnoque** [comment]
Present in NEMESIA, unless maybe design changes will be required?
