### ISSUE TITLE
Crash when upgrading 2x fragmentmothf

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#239]
"My game crashes consistently after finishing study on the Moth 12 to the 14 variant. I have the Player log and save.json attached below."

[Attachments.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10175190/Attachments.zip)

I can reproduce. The player.log suggests that the epiphany xtrigger tries to run on both lore fragments, but one has already been removed (lore -1 or epiphany, idk)

Only one report thus far, so I'm assuming there is something more about the case.

**Comment by Chelnoque** [comment]
Case of Console Usage. 
(that revealed an actual bug, to give it justice, but anyways, this crash can't occur in natural environment)

Here's the cleaned, uncrashing save:
[save.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10175442/save.zip)

**Comment by alexiskennedy** [comment]
Perfect.
