### ISSUE TITLE
Console behind ctrl

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#240]
alexis
waaaaiit a minute
OK, years ago I changed the dev console so it only opened with ctrl + ~
I always open it with ctrl + ~
which works
I now learn that just ~ works, again (edited) 
I assume I did that by accident when I reworked the UI to use the new InputSystem?
so absolutely, extremely happy to change it to ctrl + ~
I thought they wanted something more obscure than that

as discussed!

**Comment by Chelnoque** [comment]
Done in NEMESIA.
