### ISSUE TITLE
Multi-card selection makes the cards fly away

### ISSUE THREAD

**Issue by Klaim** [weatherfactory/cultistsimulator-visible#241]
# Context

MOTORCHID build, but this issue was observed in at least 1 ulterior version. I didn't try to do that before that version.

# How To Reproduce

While holding the Shift/Maj key, left-click on multiple separate (not stacked) cards. The cards are all selected with a white highlight. Then move the selected cards somewhere else by dragging them.

# Observed

The selected cards move when the mouse move in a spiral motion, changing size (or depth position?). Once we release the dragging, the cards ends up somewhere on the table, most likely in one of the corners, as if projected with terrible force.

# Expected

The cards follow the movement of the dragging mouse, keeping their position relative to the mouse. They don't fly away when we stop dragging them and just end on the grid where we left them. They also don't move in spiral motion while dragging or change size/depth-position either.

# Additional Notes

I made a video reproducing the issue: https://drive.google.com/file/d/1Fn46xqQdNHFS_OHbVCVQcl8muWvWpRAD/view?usp=share_link

**Comment by Chelnoque** [comment]
Thanks for the report and sorry for the wait!
Fixed in ORACHE.
