### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#242]
- nothing obvious in player.log
- save.json reverts to new game on load??

[Downloads.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10331988/Downloads.zip)

**Comment by alexiskennedy** [comment]
Save does _not_ revert to new game on load, that was me being silly

User says he hasn't seen recurrence, so making even lower pri

**Comment by Chelnoque** [comment]
Nothing non-obvious either, alas. 
Since today, we're logging an entire stacktrace every time we're entering the cat screen.

**Comment by alexiskennedy** [comment]
❤️
