### ISSUE TITLE
'Varley' resurgat

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#243]
hs 7379

>>>>>>>> 18:19: Catch for 'Varley', which should no longer occur now we've removed the OnPointerExit->ExecuteEvent from CardManifestation OnPointerExit... but let's be safe. Exception: System.NullReferenceException: Object reference not set to an instance of an object
[Attachments.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10332036/Attachments.zip)

**Comment by Chelnoque** [comment]
Varley warning, but not Varley bug - the error was caused by the credits/version news. The actual reason is that there's no Meniscate and trying to access it in OnPointerExit() caused nullreference.
