### ISSUE TITLE
Mod-related (Roost Machine related? idk) crashes on n.2

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#244]
[Attachments (2).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10332072/Attachments.2.zip)
[Attachments (1).zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10332073/Attachments.1.zip)

hs 7392, hs7391

**Comment by Chelnoque** [comment]
This happened for a brief period after n.2 release. Can be resolved by manually updating the Roost (unsubscribing/resubscribing), but most likely self-resolved by now.
