### ISSUE TITLE
Minor Exile issue

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#248]
If the diagnosis is right this is prolly a JSON tweak?
==
was attempting to go for more achievements, this time being the Lionsmith side of the Corrivalry, and it appears I had found a bug during my final showdown with the Foe. Attempting to use Biedde's Blade had it function as intended, giving a wound that would take Duffoure twice as long to heal. However, when attempting to attack again with Biedde's Blade and reinforcing it with The Shattered Mysteries, it had only produced a standard wound instead.

(It also happened when attacking via the lore and reinforcing with the Blade.)

Since I was playing with Sneakwork's Exile: Betrayer's Map, I first checked to see if this was a mod issue or a base game code issue, which he and a few other coders quickly checked and confirmed it was the latter. According to the frangiclave, it's to do with striking.foe resulting in wound.foe.unstanchable, but striking.foe.weapon only leads to wound.foe instead.

**Comment by Chelnoque** [comment]
Ah, yes, this one is cult classic! A real honour to fix.

**Comment by Chelnoque** [comment]
Fixed in ORACHE (we will miss you)
