### ISSUE TITLE
Reduced Mansus volume and camera smoothing

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#249]
As discussed here https://steamcommunity.com/app/718670/discussions/0/3719440678458550789/ and in our Slack thread. Pri 5 cos I made a point of promising it.

**Comment by Chelnoque** [comment]
Fixed in ORACHE. Removed camera movements entirely, after all - least intrusiveness and the nebulous benefit otherwise.

**Comment by alexiskennedy** [comment]
I suspect this may itself provoke further feedback. Let's see.
