### ISSUE TITLE
"The cat made me do it"

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#251]
hs 7513
[Player.log](https://github.com/weatherfactory/cultistsimulator-visible/files/10545095/Player.log)
[mods.txt](https://github.com/weatherfactory/cultistsimulator-visible/files/10545097/mods.txt)

**Comment by alexiskennedy** [comment]
[save.json.txt](https://github.com/weatherfactory/cultistsimulator-visible/files/10545192/save.json.txt)
(renamed save extension for reasons)

**Comment by Chelnoque** [comment]
Mod issue - "Looping Jobs" has an invalid JSON. Not the first time it is reported, and, alas, probably not the last.
You can suggest the player to use this one instead: https://steamcommunity.com/sharedfiles/filedetails/?id=2823487280
