### ISSUE TITLE
Double-counted Passion?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#252]
"Also, at least for Passion, the exhausted card count is double-counted. I.e. if you have two Passion and they're both exhausted, it will say you have 4 exhausted passion."

"What do you know, but I stumbled on the passion bug again. Attached are the two .jsons. This was on Nemesia, on a Windows 10 computer.

In case it's not obvious from the log, the passion was exhausted due to dreaming about the Wood."
-
AK adds: I remember this was a bug a long time ago...

[Attachments.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10545198/Attachments.zip)

**Comment by Chelnoque** [comment]
The problem, as far as I can tell, only affects the status bar (now you can see what I meant that it's "is a bit more hardcode-y/unstablethat it ough to be").

**Comment by Chelnoque** [comment]
Aspects not updating, I thought? Mayhaps caching problems? Spheres contributing their aspects twice? But only for passion, not for any other element? What can cause something that very-very specific? 
In reality:

```elementCounts[i].SetFatiguedCount(AspectValue("passionexhausted") + AspectValue("passionexhausted"));```
It downright stacks the value with itself. The actual one is a bit more verbose so it's easier to overlook; and it supposed to sum the values of "passionexhausted" and "disillusionment" - two different kinds of exhausted passion. Somewhere in the stream of updates, one string was forgotten and weren't renamed. So we lived in a world where the exhausted passion was x2, and nobody noticed. And even those who noticed thought that it was something new.

**Comment by alexiskennedy** [comment]
>disillusionment 

Man, this takes me back. In another History I would have loved to focus more on transformations between different kinds of mental state card... but we went down other avenues, ofc.
