### ISSUE TITLE
Backwards compatibility for Stored/CircleManifestation

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#258]
Vortex's work on circle-displayed elements looks good, but unfortunately it also affects CS.

I thought this would just be a simple switch for ManifestationType, but there's also something in the code that makes storedmanifestations display in a different position on CS windows?

We need to fix this before the next release that uses this code, but obviously not until then. It might be a good opportunity to do some related cleanup. Just putting it in now before I forget.

For the total avoidance of doubt, all the BOH stuff still takes priority

**Comment by Chelnoque** [comment]
Fixed in PEONY.
