### ISSUE TITLE
"A mislabeled (?) interaction?"

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#259]
studied with Contentedness (Lantern 2 + Heart 2), Winter Influence 2 and Heart Lore 6.
The game says this will improve my Lantern influence.
It results in "Luminosities Aligned" but the output is: Winter influence 6, Heart influence 6 and the Heart Lore 6 that was used as the catalyst.
There is no Lantern in the output at all.
It didn't seem like you intended it to work that way.

(hs8380)

**Comment by Chelnoque** [comment]
Roughly the same thing as https://github.com/weatherfactory/cultistsimulator-visible/issues/4 but with much more nuance. Pehaprs it is time to untangle the contentment upgrading.

**Comment by Chelnoque** [comment]
Fixed in PEONY.
