### ISSUE TITLE
Duplicate commission outputs

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#261]
" am running The Aspirant on the Orache build, and noticed this:

If you talk to a Patron to get a Commission, you can Work in the Commision more than once, and get a duplicate manuscript for each work, but you can only submit one manuscript back to the Patron. The remaining manuscripts cannot be used or sold, and remain forever in the game."

(this may of course have been the case already...)

**Comment by Chelnoque** [comment]
Yep, this was always the case. Although
a) you *can* use the remaining manuscripts when the same comission pops up again next time (and even for other comissions of the same type if they have lower level reqs)
b) I think some people just enjoyed collecting them?

I admit it can be confusing, so maybe worth preventing work on the same comission if one is present on the board already - nothing that extantreqs can't solve.

**Comment by alexiskennedy** [comment]
I think leave it. One bug report every three years I'm chill with. We could use extantreqs and purge commission_of_type, but some people might _want_ to build up a backlog of commissions for whatever reason. It was only the reference to ORACHE that got my attention. ta!
