### ISSUE TITLE
Sunset Rite Should Consume Offerings?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#262]
hs9362, didn't specify if beta

Steps to Reproduce:
Utilize the Sunset Rite ritual to perform a summon.
Enter a valid combination, utilizing an Influence in the Offerings.
Wait for successful completion (not a failed summon)

What I expect:
The Influence should be consumed / removed from the board.

What's actually occurring:
The Influence returns from the ritual and remains on the table.

Notes:
I anticipated the influence being consumed as part of the ritual, primarily because the description of the Sunset Rite Offering will be consumed.

This bug makes it more difficult to control unruly Influences that decay into Fascination or Dread."

**Comment by Chelnoque** [comment]
Working as intended 🤷‍♂️
