### ISSUE TITLE
Stag Door results not random?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#3]
User report below. I would usually be inclined to assume user error / statistical naivety, but user has submitted very credible reports alongside. So logging in case.

--
14. Stag Door results not random
I already reported this on Twitter but I get three results in Stag Door overwhelmingly more often than others (some combinations I haven't seen ever). Curiously these three combinations contain all possible cards and no card repeats in either.
(Order: Stag Door - Painted River - The Ascent of Knives)
Trembling Heat - Erudition: Lesson Learnt - Bitter Atmosphere
Forgotten Chronicle - Forbidden Epic - An Urgency of Appetite
Subtle Rupture - Fascination - Furious Air

I just entered the game and entered the Stag Door three times and what results did I get?
Trembling Heat - Erudition: Lesson Learnt - Bitter Atmosphere
Forgotten Chronicle - Forbidden Epic - An Urgency of Appetite x 2

Not a statistical impossibility (nothing is), but I think quite uncanny. Across 400 hours of gameplay, no less.

**Comment by alexiskennedy** [comment]
Initial reporter has garnered more eyewitness testimony.

gibsoncrab:
Honestly, I've come to rely on this behavior since the stag door is my most used entry into the Mansus until I can get Frangiclave.

StrawbewwieSundaeUwU:
I've noticed this too. Thought it was intentional, to the point where I've (almost) learned when to pick which hidden card option based on the showing card. Becomes an op tactic when you have a stable and relatable Way like Stag with tons of reason. It's a bug?

BillTheNecromancer:
I've gotten 91% of the achievements and I can definitively say that for me, this is extremely consistent. It's so consistent that I only even see any configuration to the contrary just about 3-4 times a playthrough.

**Comment by gamercoon** [comment]
I certainly thought this was intended and an artifact of how the cards are drawn, and there being the same number of possible draws for each door at this gate.  I have noticed that it seems to be 100% consistent which face-down cards are paired with a given face-up card as long as I keep selecting a face-down card (I usually keep picking painted river over and over), but if I select one of the face-up cards then the combinations change *I think*.  Something seems to get them re-aligned again to the normal combinations later, but I'm not sure what it is exactly.  Exiting and re-loading is one thing, but it is not actually necessary.

**Comment by gamercoon** [comment]
Yeah, that makes sense and is the behavior I figured you intended, even though I like the current behavior :)

I don't think the Birthday Paradox would explain this.  There are 6 permutations of each deck, creating 216 sequences you could see in 3 visits to the stag door.  Plus, it's far too consistent for that.

The behavior I thought I was observing was that the face-down cards are not actually drawn and destroyed unless they are revealed (so choosing the face up card would alter which ones are drawn with the face up card), and when the decks are empty the discard piles are either "turned over" maintaining the same order, or shuffled in exactly the same way as each other such that the cards still align.

I suspect the decks are being shuffled in the same way as each other; this would explain the alignment behavior (though I'm not sure why selecting the face up card would change that).  I'm not familiar with the programming language you're using (VB maybe?), but if I assume that around the code you posted is something along the lines of
```
foreach(deck in stagDoorDecks)
    //(code that you posted)
```
then I think I can explain the behavior.  According to the documentation here `https://docs.microsoft.com/en-us/dotnet/api/system.random.-ctor?view=net-6.0` your code `new System.Random();` creates an object that will generate a sequence of pseudo-random numbers using the system time as a seed.  The code shuffling the deck looks very lightweight, and probably will execute fast enough that the system time has not changed by the time you get to the next deck, so your next `new System.Random();` will generate the same sequence for the next deck, and the next one.  This could easily be solved by passing in your own seed value (and changing it between each call), by using a single instance of the Random class for all your random number generation, by making sure some time has elapsed between instantiations of the Random class (this would be bad for performance of course), or by moving the instantiation outside the deck loop like this:
```
         var r = new System.Random();
         foreach(var fromDeckSpec in stagDoorDecks)
            var permittedCards = fromDeckSpec.Spec.Except(forbiddenCards);
            foreach (var card in permittedCards.OrderBy(x=>r.Next()))
                drawPile.ProvisionElementToken(card, 1);
```

**Comment by alexiskennedy** [comment]
I think you're right... and now I feel bad because I asked about this on Twitter, had similar responses, made the change for 2022.3.a.3...

![image](https://user-images.githubusercontent.com/228608/156735064-06b2c259-17d9-4dee-991a-2d3fb91dc5be.png)

...and forgot to update this issue! so you typed out the extremely helpful comments above after I had already committed the change. Sorry about that. Thank you for being so helpful anyway.

**Comment by gamercoon** [comment]
Ah, alright.  I'll be sad to see this behavior go, I imagine I'm not the only one who developed a portion of their whole game strategy around it :P

**Comment by alexiskennedy** [comment]
If I'm incredibly flush with time (unlikely) I'll add a bird/worm slider back that returns it.
More likely: I'll remember that randomness isn't always best for BH design.
