### ISSUE TITLE
Recipe eligibility issue when upgrading lore with Contentment in the mix

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#4]
" Study: A Consciousness of Radiance + Contentment + Lantern Lore
Results in a text "Interweave the Rhythms unceasing" and the follow-up "I've intensified this Heart Influence" which is wrong, as we're intensifying Lantern Influence."

This is correct. The Heart influence upgrade recipe sees the Heart influence in Contentment, and grabs control. It's minor and a nuisance to fix though.

**Comment by alexiskennedy** [comment]
@Chelnoque was this one fixed by your last round of lore upgrade work? I imagine not, but I wanted to check

**Comment by Chelnoque** [comment]
@alexiskennedy No, ILEX only affects lore upgrades. This needs a different look.

**Comment by Chelnoque** [comment]
Same as https://github.com/weatherfactory/cultistsimulator-visible/issues/259, fixed in PEONY.
