### ISSUE TITLE
Is there a way to make funds stack automatically?

### ISSUE THREAD

**Issue by KostberaLili** [weatherfactory/cultistsimulator-visible#46]
e.g. 
there is a stack of funds on the table, and another fund-card could be collected from the work verb:
![%IY@DXDSKEUB49HHSJ1}IN9](https://user-images.githubusercontent.com/72067242/156926612-f67d642d-a2fe-4a97-ba22-74ce776a3144.png)
however, the newly-collected fund would not stack with the other fund-cards that are already existing, but it appears in the area for new cards:
![3FUM B_8~6`{SQACCC P%_L](https://user-images.githubusercontent.com/72067242/156926683-d928028f-a9c5-4d6e-b2b2-d66ab4354792.png)
it sort of makes the arrangement of cards a bit more tiring (in my opinion), so i'm wondering if this can be changed in a later patch?

**Comment by alexiskennedy** [comment]
In next patch, cheers :)
