### ISSUE TITLE
Disappearing card: Glover & Glover

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#72]
hs 5985
- Glover & Glover job disappears. I'm not completely sure what triggers this, but sometimes, when collecting the cards from the job (i.e. funds, exhausted reason), the job just vanishes. This happens for both the senior position and the non-senior position.

- Glover & Glover thinks I'm not working. This is probably somewhat reproducible via my save file. I collect the cards from the job, and instead of getting the job back, I get the whole "Job, but you haven't been working and need to use passion to get it back" card.

**Comment by Vaevictusnet** [comment]
[Cultist Simulator.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/8228930/Cultist.Simulator.zip)
Appdata directory included.

Seems the same thing happened to me.  I was dragging it from it's normal spot to the work square and may have missed or something but it seems to be gone now.

I have searched for my glover & glover card now... not finding it.
I believe i lost an erudition earlier "where'd that go" kinda thing... but that's no big deal, so i ignored it.  Glover and Glover is a bit more of a problem, though i could start selling paintings.

Good luck

**Comment by alexiskennedy** [comment]
Got it! Thank you everyone.

https://youtu.be/cy9Vd7Hjrfs

**Comment by Vaevictusnet** [comment]
sorry, alexis, i just did it again, post patch.
i'm sure my method this time though...
I used C to collect the job, post work, and then
[Cultist Simulator.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/8235880/Cultist.Simulator.zip)
 drug it from the desktop to the work ... and missed to the left... still on the action popup but off to the left.  I didn't have recording on or i'd supply it.  save file attached.

**Comment by Vaevictusnet** [comment]
i doubt it's relevant, but i tried to change the card grid to 1 card just before that.

**Comment by Vaevictusnet** [comment]
there's a chance i didn't have the current version running... disregard for now.  I'll be sure this time.

**Comment by alexiskennedy** [comment]
Ta V. Your player log says 2022.3.j.1, so it is the current version, but this is definitely a different bug. I'll open as a new issue

**Comment by Vaevictusnet** [comment]
[Cultist Simulator.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/8236584/Cultist.Simulator.zip)
just did it a 3rd time, this was definitely on the current version.  I'm an IT guy/coder/etc ... and this save is within the 60s after losing it... i think i dropped it badly too far right this time.
Is there anything i can do to assist further?

**Comment by Vaevictusnet** [comment]
got a video this time
[2022-03-11 18-13-31-1.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/8236667/2022-03-11.18-13-31-1.zip)
looks like i clicked the (C)ollect button and then dropped badly (on purpose maybe?)
