### ISSUE TITLE
Garbled Action Text

### ISSUE THREAD

**Issue by Vaevictusnet** [weatherfactory/cultistsimulator-visible#79]
![image](https://user-images.githubusercontent.com/472789/158022871-c887ac1f-2b37-45dd-a564-37571c47911d.png)
![image](https://user-images.githubusercontent.com/472789/158022880-d9b8c890-a39d-4b81-93bb-d29afd9e21d5.png)

text on all Action messages seems to be overwriting itself

**Comment by Vaevictusnet** [comment]
>>>>>>>> Cultist Simulator Version: 2022.3.k.1
OS: Windows 11  (10.0.22000) 64bit
Processor: Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz Count: 8
Graphics: 7812/NVIDIA GeForce RTX 2070 SUPER/NVIDIA/Direct3D 11.0 [level 11.1]/3072 Shader: 50

**Comment by alexiskennedy** [comment]
yeah, I should stop coding now. Pushed a hotfix, thanks for flagging this :)

**Comment by Vaevictusnet** [comment]
thanks for the fix, good luck with your re-trial by fire.  You have my respect and sympathy.
