### ISSUE TITLE
Super Minor: Gridsnap issue

### ISSUE THREAD

**Issue by Vaevictusnet** [weatherfactory/cultistsimulator-visible#80]
at half-card gridsnap, cards sometimes avoid being adjacent to other cards.
Appears to be what happens when you try to stack...

Also, the light wireframe for dropping the cards is very hard to see, perhaps just go a full card drop shadow?

Video of bad snapping:
[2022-03-12 10-00-42.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/8237894/2022-03-12.10-00-42.zip)

**Comment by alexiskennedy** [comment]
>full card drop shadow?

I originally did this, but the effect of a shadow-like object hat moves randomly is something like seasickness. I've tuned up the alpha on it tho

Big gridsnap patch just dropping now.
