### ISSUE TITLE
Disappearing card: 'Esau'

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#82]
There is a nasty reproducible bug!!!!!!
Put 1 Vitality in the Study action slot, then quickly drag that first Vitality over to the second slot. The slot will disappear and so will that Vitality. This works with any similar action.

**Comment by Vaevictusnet** [comment]
Confirmed
[2022-03-13 01-18-52.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/8239117/2022-03-13.01-18-52.zip)
.

**Comment by alexiskennedy** [comment]
repro'd. Sadly this may be distinct from 'Boojum' tho
