### ISSUE TITLE
Changed Behaviour on Consuming Slots and Order of Operations

### ISSUE THREAD

**Issue by superjw2** [weatherfactory/cultistsimulator-visible#83]
This may be intentional, but the behaviour is different from before the updates, so I'm reporting it just in case.

Previously, elements in a consuming slot were included when considering requirements for alt-additional recipes, then destroyed after that. Now, elements seem to get destroyed before the requirements for alt-additional recipes are considered. I don't think any base-game recipes are affected by this, I noticed it while modding.

**Comment by alexiskennedy** [comment]
It is intentional, but it might not have been, so thank you for reporting it.

> I don't think any base-game recipes are affected by this

Nor did I, but I found out otherwise! This was what was breaking the hireling recruitment in Talk. There may be a couple of others. I'm going to leave this open as low-pri in case anyone spots one.
