### ISSUE TITLE
recipe id sometimes showing instead of label. 

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#91]
Linked recipe prob?
--
            "id": "priest.repevent",
            "actionid": "priest.repevent",
            "label": "Exultation",
            "startdescription": "Sometimes, my words - and those I have borrowed - move my congregation beyond mere concentration, to exultation.",

**Comment by alexiskennedy** [comment]
"C. The description for An Escaped Summoning has Ravaged your Dreams reads: ".deceiver_haunting_reason_middeceiver""

**Comment by alexiskennedy** [comment]
(This might now be fixed. March is a blur.)

**Comment by Chelnoque** [comment]
Both recipes, spawned natively, display correct labels (currently). Nothing in the code suggests it can use IDs instead of labels.
