### ISSUE TITLE
OverrideVerbIcon issue with modding support?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#94]
User with a whole shebang of mods here: hs6107

**Comment by Genroa** [comment]
A few more informations about that: when using an element with the verb icon property, even when the verb seems to display the correct new image when closed, it displays the original image in its upper left corner when you open it.

**Comment by alexiskennedy** [comment]
The given key '{
  "$type": "SecretHistories.Commands.TokenCreationCommand, SecretHistories.Main",
  "Location": {
    "$type": "SecretHistories.UI.TokenLocation, SecretHistories.Main",
    "Anchored3DPosition": {
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "AtSpherePath": {
      "$type": "SecretHistories.Fucine.FucinePath, SecretHistories.Main",
      "Path": "~/situationsmalleary"
    }
  },
  "Payload": {
    "$type": "SecretHistories.Commands.ElementStackCreationCommand, SecretHistories.Main",
    "Id": "!funds_24",
    "EntityId": "funds",
    "Quantity": 1,
    "Mutations": {
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Int32, mscorlib]], mscorlib"
    },
    "Illuminations": {
      "$type": "System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.String, mscorlib]], mscorlib"
    },
    "Defunct": false,
    "LifetimeRemaining": 0.0,
    "Dominions": []
  },
  "Defunct": false,
  "CurrentState": {
    "$type": "SecretHistories.States.TokenStates.DroppedInSphereState, SecretHistories.Main"
  }
}' was not present in the dictionary.: 
   at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <00c558282d074245ab3496e2d108079b>:0 
  at EntityStore.GetById[T] (System.String entityId) [0x0000d] in <8c8afdf3f0f344bb94117892c249eba1>:0 
  at Compendium.GetVerbIconOverrideFromAspects

**Comment by alexiskennedy** [comment]
> A few more informations about that: when using an element with the verb icon property, even when the verb seems to display the correct new image when closed, it displays the original image in its upper left corner when you open it.

This is something different, I think. I'll add your point as another issue cos it's higher pri than 'unconfirmed nullref exception for mods maybe'

**Comment by alexiskennedy** [comment]
(I mean not *much* higher pri now I think about it)
