### ISSUE TITLE
Poor resolution on Retina mac displays -- at first

### ISSUE THREAD

**Issue by nickolaos** [weatherfactory/cultistsimulator-visible#99]
Retina Macbook Pro 2016 - macOS Monterey 12.3

What's notable:

Issue 1. Initially, the game does not scale properly to 16:10 resolutions. In my case, 2880x1800.
Issue 2. Initially, the visuals look stretched and generally low-quality.

3a. These can both be resolved by changing the resolution slider from 3360x2100 to 2880x1800.
3b. Interestingly, setting the resolution back to 3360x2100 doesn't bring the problems back.
3c. These issues don't come back after fixing them the first time, even on game restart.

Two screenshots showing the initial state and the resolved state: 

Initial State
<img width="1680" alt="Screen Shot 2022-03-15 at 4 21 08 PM" src="https://user-images.githubusercontent.com/18318058/158476736-e429c1fc-d7e1-4302-a0c3-36fed30694b3.png">

Resolved State
<img width="1680" alt="Screen Shot 2022-03-15 at 4 35 22 PM" src="https://user-images.githubusercontent.com/18318058/158476774-816c7990-b944-47d3-8087-0a3290b11ebc.png">

**Comment by alexiskennedy** [comment]
Ta. Did you have any problems running it on Monterey and/or do you get a player.log? I have a weird Mac crash in #96

**Comment by nickolaos** [comment]
No crashes on Monterey, but the game is hard to play due to the card placement issue you are working on fixing. In addition, switching the movement controls to WASD sometimes triggers the name entry field.
